### ISSUE TITLE
infinigen/worldgen/terrain/lib/cuda/elements/ground.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by maciekpoplawski** [princeton-vl/infinigen#14]
Crashed: 0 fineterrain_0_0_0048_0 25433781102  Error: Python: Traceback (most recent call last):,Error: /home/maciek/PROJEKTY/infinigen/worldgen/terrain/lib/cuda/elements/ground.so: cannot open shared object file: No such file or directory fatal=True 06/18 08:58PM

**Comment by stallboy** [comment]
I have the same problem include your first "SoilMachine.so: cannot open shared object file" . 
after a second check, here is what I found.
the reason was my network CANNOT access git://.       ( in .gitmodules file)
so the solution is: change  the git:// to https:// in .gitmodules file. then:

git submodules deinit --all -f
bash install.sh
