### ISSUE TITLE
How to integrate Infinigen with Unity

### ISSUE THREAD

**Issue by XeuniceX** [princeton-vl/infinigen#159]
**Describe the feature you would like to see implemented**
I would like to see a full 3D scene generated on Unity. I also want to use the Infinigen framework using Unity by inputting my own images.

**Comment by araistrick** [comment]
You can attempt to export whole scenes to USD or similar formats using blender's tools and import them into unity. You can also export individual assets as described in our docs then import them.

RE "inputting my own images", this is not possible since Infinigen contains no AI and does not natively accept a language or image prompt, see my response to #164
