### ISSUE TITLE
Infigen PyPI Package

### ISSUE THREAD

**Issue by lalalune** [princeton-vl/infinigen#253]
Hey there!

We've been building infinigen to PyPI and working out the bugs on that. I accidentally reserved the infinigen package instead of publishing to our rr-infinigen package since the main infinigen is unclaimed. I'm a little worried that if I delete it, the package might not be reservable again and I'm also a little worried that if nobody is reserving the package name, someone rogue could come along and do that.

I would like to transfer ownership of the `infinigen` package on PyPI to the team, or we can continue to maintain it.

Thanks <3

**Comment by araistrick** [comment]
Hello, yes we would definitely like to own the `infinigen` project on PyPi, no worries for accidentally publishing but we will need to transfer it asap somehow.

I had a pending hold on the project name which I thought would secure it but I just got an email saying that someone had registered it and my pending project was revoked. 

For now please [transfer ownership](https://discuss.python.org/t/transferring-a-pypi-name-to-someone-else/7196/2) of the project to username `princeton-vl`, then I will publish a placeholder project there for now so that people dont accidentally download this version.

**Comment by lalalune** [comment]
I was not able to transfer ownership outright:
<img width="852" alt="Screenshot 2024-06-13 at 1 31 39 PM" src="https://github.com/princeton-vl/infinigen/assets/18633264/a68e1f7c-bc3d-4b2b-888f-c0d1eb4641a1">

However, I added `princeton-vl` as an owner:
<img width="846" alt="Screenshot 2024-06-13 at 1 31 33 PM" src="https://github.com/princeton-vl/infinigen/assets/18633264/947d6f80-9f99-458d-84f2-f9e8c30e1e06">

Look out for an invite

**Comment by araistrick** [comment]
Thanks for your help, I have completed the transfer & taken ownership of the project. We will do our best to actively maintain it starting ASAP after we wrap up our WIP release.
