### ISSUE TITLE
Can I import other forms of 3D models (such as OBJ or gltf) into Blender UI to implement new assets?

### ISSUE THREAD

**Issue by SearAbbas** [princeton-vl/infinigen#270]
**Describe the feature you would like to see implemented**
Hi, I am not very familiar with Blender, and I would like to ask if I can import a pre made 3D model (such as OBJ or gltf) into Blender UI and use Node Transformer to convert it into Python script to implement new assets.

**Comment by araistrick** [comment]
Hello, you can import existing assets into blender as normal using their api e.g. https://docs.blender.org/api/current/bpy.ops.wm.html#bpy.ops.wm.obj_import. This will make the specific OBJs you have access to appear in the scene, and you can position them using blender's API.

However, it is impossible to transpile a non procedural asset (such as an OBJ file) into a randomized procedural asset. This is not a limitation of our system, this type of request is simply impossible, since the OBJ file does not contain any procedural code to begin with.

The only inputs accepted by the Node Transpiler are blender node graphs (geometry nodes, material nodes, etc). OBJ/gltf files do not contain these.

**Comment by SearAbbas** [comment]
> Hello, you can import existing assets into blender as normal using their api e.g. https://docs.blender.org/api/current/bpy.ops.wm.html#bpy.ops.wm.obj_import. This will make the specific OBJs you have access to appear in the scene, and you can position them using blender's API.
> 
> However, it is impossible to transpile a non procedural asset (such as an OBJ file) into a randomized procedural asset. This is not a limitation of our system, this type of request is simply impossible, since the OBJ file does not contain any procedural code to begin with.
> 
> The only inputs accepted by the Node Transpiler are blender node graphs (geometry nodes, material nodes, etc). OBJ/gltf files do not contain these.

Thanks!
