### ISSUE TITLE
Indoor Scene Generation also generates outdoor terrain

### ISSUE THREAD

**Issue by SergioArnaud** [princeton-vl/infinigen#289]
The command provided in the readme to automatically generate indoor scenes takes too long (2 hours) the reason is that it's unecesarilly generating all the terrain of the outdoor scene, see img

I added the **fast_solve.gin** and now it takes ~20 mins (there might be a better way tho, but the main idea is to not generate the outdoor terrain when generating indoor scenes). Example command below:

```
screen python -m infinigen.datagen.manage_jobs --output_folder outputs/my_dataset --num_scenes 1 --pipeline_configs local_256GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin --configs singleroom.gin **fast_solve.gin**--pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.restrict_single_supported_roomtype=True 
```

| Before | After |
|--------|-------|
| ![Before image](https://github.com/user-attachments/assets/d47278c9-0c6a-4672-a9cd-2d54b2dc7a41) | ![After image](https://github.com/user-attachments/assets/6cf1c7a7-174f-4bd9-828b-fca50c46f4a6) |

**Comment by David-Yan1** [comment]
FYI, a big portion of the speed up is likely from the shorter solving rather than no terrain (although terrain generation does take some time). The `fast_solve.gin` config typically results in sparser and less "arranged" scenes since the solver runs for far fewer steps. If you still want to fully solve scenes without terrain, you can add the override `compose_indoors.terrain_enabled=False` without using `fast_solve`. Likewise, you can use `fast_solve` with terrain by adding `compose_indoors.terrain_enabled=True`, since fast_solve turns off terrain by default.

**Comment by SergioArnaud** [comment]
Thanks for the context @David-Yan1! This answers my concern.
