### ISSUE TITLE
Compute config Advice

### ISSUE THREAD

**Issue by SergioArnaud** [princeton-vl/infinigen#292]
Could you advice me on which would be an ideal config file for my hardware? Bellow the specs:

```
GPUs: 8
GPU RAM: 32GB per GPU, 256GB in total
GPU Model: Nvidia Tesla V100

CPU cores: 80
CPU RAM: 6.25GB per GPU, 500GB in total
CPU Model:    Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
```

I've tried modifying the local_256GB.gin file and I got it working relatively well, Nevertheless I'm not fully exploiding my hardware and given that there are many things to account for I'd value your advice

**Comment by araistrick** [comment]
By "not fully exploiting" I presume you mean that the GPUs are not well utilized.

The best solution to this is to render many images for each 3D scene you create, since rendering is GPU bound and scene generation is CPU bound.

Video is a good way to do this, or you can simply render from many viewpoints per scene by adding `--pipeline_overrides iterate_scene_tasks.cam_id_ranges=[20,2] --overrides camera.spawn_camera_rigs.n_camera_rigs=20 compute_base_views.min_candidates_ratio=2 compose_indoors.terrain_enabled=False` which is my prefered setting on the current code.
