### ISSUE TITLE
Size of exported usdc file is 2kb and it completes processing immediately. I don't think it's a valid export

### ISSUE THREAD

**Issue by andytriboletti** [princeton-vl/infinigen#330]
# Describe the bug
I ran teh sample code to produce a scene hello world. The scene.blend file it created is 934 MB. I looked at the images folder and it looks correct. When I ran the export to usdc command it completed immediately and the size of hte file is very small
### What version of the code were you using? 
Tell us the commit & commit hash from `git log`

### What command did you run?
(infinigen) andy@andys-pc:~/infinigen/outputs/hello_world/0/fine$ python -m infinigen.tools.export --input_folder .  --output_folder outputs/my_export -f usdc -r 1024

### What are your FULL output logs?
Provide the FULL output logs from your command as a txt file.
(infinigen) andy@andys-pc:~/infinigen/outputs/hello_world/0/fine$ python -m infinigen.tools.export --input_folder .  --output_folder outputs/my_export -f usdc -r 1024
Failed to open dir (No such file or directory): /run/user/1002/gvfs/
Skipping non-blend file MaskTag.json
Skipping non-blend file assets
Skipping non-blend file outputs
Skipping non-blend file pipeline_fine.csv
Skipping non-blend file polycounts.txt
USD export of 'outputs/my_export/export_scene.blend/export_scene.usdc' took 18.8 ms
updating: outputs/my_export/export_scene.blend/ (stored 0%)
updating: outputs/my_export/export_scene.blend/export_scene.usdc (deflated 45%)
Skipping non-blend file scene.blend1
Skipping non-blend file version.txt
### If this is your first time running Infinigen, what are the full install logs?**
Run `pip install -v -e . > logs.txt 2>&1` and send logs.txt as an attachment.

### Platform
- OS & OS Version: 
- GPU (?) :
- GPU Driver Version (?) :
- RAM (GB):

# Additional context

**Comment by andytriboletti** [comment]
In export_logs.log I see:
INFO:root:Exporting to directory export_folder=PosixPath('outputs/my_export/export_scene.blend')
INFO:root:Deleting placeholders collection
DEBUG:root:Triangulating Meshes
DEBUG:root:Triangulating <bpy_struct, Object("Cube") at 0x3b30758>
INFO:root:---------------------------
INFO:root:Camera
INFO:root:Not mesh, skipping ...
INFO:root:---------------------------
INFO:root:Cube
INFO:root:UV Unwrapping
INFO:root:Material.001
INFO:root:Material.001 has no procedural input for DIFFUSE, not using baked textures
INFO:root:No necessary materials to bake on Cube, skipping bake
INFO:root:Material.001
INFO:root:Material.001 has no procedural input for ROUGHNESS, not using baked textures
INFO:root:No necessary materials to bake on Cube, skipping bake
INFO:root:Removed extraneous UV Layer <bpy_struct, MeshUVLoopLayer("UVMap") at 0x3c37008>
INFO:root:Reapplying baked texs on Material.001
INFO:root:Trivial shader graph, using old BSDF
INFO:root:---------------------------
INFO:root:Light
INFO:root:Not mesh, skipping ...
INFO:root:Exporting file to export_file=PosixPath('outputs/my_export/export_scene.blend/export_scene.usdc')

**Comment by christian-jacobsen** [comment]
Currently experiencing the same issue

**Comment by haran-sbs** [comment]
Currently have the same issue

**Comment by ben-martinez** [comment]
Had the same issue, the problem was that the line to read the blend file was deleted in this commit 2 weeks ago: [c01e498](https://github.com/princeton-vl/infinigen/commit/c01e498ed864cda5caa9c526d403bb8bf3df9552#diff-598744948afb390a8888aeb96ec5e922144a7535772c41746a406716b273bfd8L764). It seems this was by mistake.

To fix, copy this line to infinigen/tools/export.py on line 764: ` bpy.ops.wm.open_mainfile(filepath=str(input_blend))`

cc @mazeyu please confirm there is no issue with reverting the delete of this line of code.

**Comment by christian-jacobsen** [comment]
Hi @ben-martinez , thank you for the help! This fix does work, but I now run in to another issue. I get this error:

Error: No valid selected objects
Traceback (most recent call last):
  File "/home/cjacobsen/miniconda3/envs/infinigen/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/cjacobsen/miniconda3/envs/infinigen/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/cjacobsen/git/infinigen/infinigen/tools/export.py", line 1037, in <module>
    main(args)
  File "/home/cjacobsen/git/infinigen/infinigen/tools/export.py", line 993, in main
    folder = export_scene(
  File "/home/cjacobsen/git/infinigen/infinigen/tools/export.py", line 767, in export_scene
    export_curr_scene(folder, **kwargs)
  File "/home/cjacobsen/miniconda3/envs/infinigen/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/cjacobsen/miniconda3/envs/infinigen/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/cjacobsen/miniconda3/envs/infinigen/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/cjacobsen/git/infinigen/infinigen/tools/export.py", line 920, in export_curr_scene
    bake_scene(
  File "/home/cjacobsen/git/infinigen/infinigen/tools/export.py", line 695, in bake_scene
    bake_object(obj, folderPath, image_res, export_usd)
  File "/home/cjacobsen/git/infinigen/infinigen/tools/export.py", line 667, in bake_object
    bake_pass(obj, dest, img_size, bake_type, export_usd)
  File "/home/cjacobsen/git/infinigen/infinigen/tools/export.py", line 472, in bake_pass
    bpy.ops.object.bake(
  File "/home/cjacobsen/miniconda3/envs/infinigen/lib/python3.10/site-packages/bpy/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: No valid selected objects

This is related to this issue here: https://github.com/princeton-vl/infinigen/issues/312#issue-2504255810
For reference, I am trying to export the scene created by the hello world demo to usdc. When I render the images or blender file, it seems that the scene generated correctly. Any ideas what might be causing this error?

**Comment by mazeyu** [comment]
> Had the same issue, the problem was that the line to read the blend file was deleted in this commit 2 weeks ago: [c01e498](https://github.com/princeton-vl/infinigen/commit/c01e498ed864cda5caa9c526d403bb8bf3df9552#diff-598744948afb390a8888aeb96ec5e922144a7535772c41746a406716b273bfd8L764). It seems this was by mistake.
> 
> To fix, copy this line to infinigen/tools/export.py on line 764: ` bpy.ops.wm.open_mainfile(filepath=str(input_blend))`
> 
> cc @mazeyu please confirm there is no issue with reverting the delete of this line of code.

This is not a mistake. I intentionally deleted it to make the file reading controlled by execute_tasks.py, the same as other tasks, coarse, fine_terrain etc. (Otherwise there is a low-poly bug issue reported by someone) But I wasn't aware that  infinigen.tools.export might be directly called. Let us take a further look and reply later.

**Comment by andyundercurrent** [comment]
Thank you mazeyu for working on the bug.

Also, glb along with usd support instancing. In the usage notes, you said only usd supports instancing. I have not tried to convert an infinigen usd to glb uet to.see if it still works cause got stuck on this bug.

1. Instancing Support in glTF/GLB:
   - glTF 2.0 (which GLB is a binary form of) does support instancing.
   - It uses a feature called "Mesh Instancing" which allows multiple instances of the same mesh to be rendered with different transforms.

**Comment by andytriboletti** [comment]
Thank you mazeyu for working on the bug.


Also, glb along with usd support instancing. In the usage notes, you said only usd supports instancing. I have not tried to convert an infinigen usd to glb uet to.see if it still works cause got stuck on this bug.


1. Instancing Support in glTF/GLB:

   - glTF 2.0 (which GLB is a binary form of) does support instancing.

   - It uses a feature called "Mesh Instancing" which allows multiple instances of the same mesh to be rendered with different transforms.

**Comment by David-Yan1** [comment]
The correct location for file reading should be 

```
 for blendfile in targets:
        if blendfile.stem == "solve_state":
            shutil.copy(blendfile, args.output_folder / "solve_state.json")

        if not blendfile.suffix == ".blend":
            print(f"Skipping non-blend file {blendfile}")
            continue
        
        bpy.ops.wm.open_mainfile(filepath=str(blendfile)) # <-- ADD THIS LINE

        folder = export_scene(
            blendfile,
            args.output_folder,
            format=args.format,
            image_res=args.resolution,
            vertex_colors=args.vertex_colors,
            individual_export=args.individual,
            omniverse_export=args.omniverse,
        )
        # wanted to use shutil here but kept making corrupted files
        subprocess.call(["zip", "-r", str(folder.with_suffix(".zip")), str(folder)])
```

Export fixes for this and associated issues will be coming in the next patch.
