### ISSUE TITLE
How to make full use of cpu?

### ISSUE THREAD

**Issue by wmkai** [princeton-vl/infinigen#335]
I have 4 GPUs and only use cpu to generate a single scene. But infinigen seems to only use 1/4 of my cpu core in the fine_terrian stage. Is there any way to make full use of cpu?
![image](https://github.com/user-attachments/assets/212a9ad4-c84b-4ace-b2ad-ae037c502cc3)

**Comment by araistrick** [comment]
To make use of more CPUs id recommend running many scenes at the same time. IE if 1 fineterrain takes up 1/4 of your CPU cores, youd just make sure that at least 4 different jobs are running at any given time. 

Generally I recommend setting `manage_datagen_jobs.num_concurrent=X` where X is your amount of ram, in GB, divided by ~15 - 20 ish. 

We generally cant make a single process take advantage of many many cpu cores since the blender API / scene state is not safe to use with multiprocessing, so itd take a lot of engineering work.
