### ISSUE TITLE
About room types

### ISSUE THREAD

**Issue by nauyihsnehs** [princeton-vl/infinigen#371]
Hello!

### I'm wondering how to specify room types so they can be sure appeared in the scene.

The [`tags.py`](https://github.com/princeton-vl/infinigen/blob/4a7dc1a809b74a2a100798ac671ce26d0a6d29c3/infinigen/core/tags.py) file lists 18 room types, but I haven't seen and don't know how to generate most of them, such as **StaircaseRoom**, **Warehouse**, **Office**, **MeetingRoom**.

### Additionally, when specifying [`restrict_single_supported_roomtype`](https://github.com/princeton-vl/infinigen/blob/4a7dc1a809b74a2a100798ac671ce26d0a6d29c3/infinigen_examples/generate_indoors.py#L166), does it only support the five scenes:
Bedroom, LivingRoom, Kitchen, Bathroom, and DiningRoom?

### What version of the code were you using? 
v1.10.0 release

### What command did you run?
./infinigen-main/infinigen/datagen/manage_jobs.py \
--output_folder outputs/batch_test \
--num_scenes 10 \
--pipeline_configs local_256GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin \
--configs fast_solve.gin \
--pipeline_overrides \
get_cmd.driver_script=infinigen_examples.generate_indoors \
manage_datagen_jobs.num_concurrent=16

### Platform
- OS & OS Version: Ubuntu 22.04
- GPU: When running the program, I didn't see it utilizing the GPU.
- RAM (GB): 1T

### Thanks in advance, the variety of scenes is important to me.

**Comment by GCChen97** [comment]
Use `restrict_solving.restrict_parent_rooms=["Bedroom"]` to specify room type. In the example home constraint file, only Bedroom, LivingRoom, Kitchen, Bathroom, and DiningRoom have defined constraints. You need to write new constraints for other room types.

**Comment by araistrick** [comment]
@GCChen97  is correct, the system only has arrangement logic for Bedroom, LivingRoom, Kitchen, Bathroom, and DiningRoom. 

The StaircaseRoom tag also gets used when generating multi-story houses. The other ones you mention (StaircaseRoom, Warehouse, Office, MeetingRoom) are unused currently.

If you populate a full house, you may also be able to get Hallway and Closet to work, since there are some constraints that apply to all rooms and will also apply to these (e.g paintings on walls, storage furniture). But I dont recommend these as single-room options.
